name: spacing_generator_tutorial
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  spacing_generator_annotation: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  spacing_generator: ^0.4.0+5
  build_runner: ^2.4.12

flutter:
  uses-material-design: true
